telegram_token: "6149565033:AAGBneYFjBx08MxEIPyekKgxIJUsVteyfhw"
openai_api_key: "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"
allowed_telegram_usernames: []  # if empty, the bot is available to anyone
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)
